/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WP;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class inputalternatif extends javax.swing.JFrame {

    /**
     * Creates new form inputalternatif
     */
    public inputalternatif() {
        initComponents();
        tampilData();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtram = new javax.swing.JTextField();
        txtpenyimpanan = new javax.swing.JTextField();
        txtgpu = new javax.swing.JTextField();
        txtlayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlternatif = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtbaterai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ALTERNATIF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(274, 274, 274))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setText("Nama");

        jLabel3.setText("Harga");

        jLabel4.setText("RAM");

        jLabel5.setText("Penyimpanan");

        jLabel6.setText("GPU");

        jLabel7.setText("Layar");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtlayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlayarActionPerformed(evt);
            }
        });

        tblAlternatif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAlternatif);

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel8.setText("Baterai");

        txtbaterai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbateraiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnama)
                            .addComponent(txtpenyimpanan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtram, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtharga, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtlayar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addComponent(txtgpu, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnkembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnhapus)
                        .addGap(30, 30, 30)
                        .addComponent(btnedit)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtbaterai, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnsimpan)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtlayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbaterai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhapus)
                    .addComponent(btnkembali)
                    .addComponent(btnedit)
                    .addComponent(btnsimpan))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtlayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlayarActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
          // Ambil nilai dari input fields dan combo box
    // Mengambil nilai dari input fields

String namaAlternatif = txtnama.getText();
String hargaAlternatif = txtharga.getText();
String ramAlternatif = txtram.getText();
String penyimpananAlternatif = txtpenyimpanan.getText();
String gpuAlternatif = txtgpu.getText();
String layarAlternatif = txtlayar.getText();
String bateraiAlternatif = txtbaterai.getText();

// Pastikan nilai tidak kosong
if (!namaAlternatif.isEmpty() && !hargaAlternatif.isEmpty() && !ramAlternatif.isEmpty() && !penyimpananAlternatif.isEmpty() && !gpuAlternatif.isEmpty()&& !layarAlternatif.isEmpty()&& !bateraiAlternatif.isEmpty()) {
    // Koneksi ke database
    Connection kon = null;
    PreparedStatement pstmt = null;
    
    try {
        // Dapatkan koneksi dari kelas Koneksi
        kon = koneksi.koneksiDB();
        
        // Query untuk memasukkan data
        String sql = "INSERT INTO alternatif (nama_laptop, harga, ram, penyimpanan, gpu, layar, baterai) VALUES (?, ?, ?, ?, ?, ?, ?)";
        pstmt = kon.prepareStatement(sql);
        pstmt.setString(1, namaAlternatif);
        pstmt.setString(2, hargaAlternatif);
        pstmt.setString(3, ramAlternatif);
        pstmt.setString(4, penyimpananAlternatif);
        pstmt.setString(5, gpuAlternatif);
        pstmt.setString(6, layarAlternatif);
        pstmt.setString(7, bateraiAlternatif);
       
        // Eksekusi query
        pstmt.executeUpdate();
        
        // Tampilkan pesan sukses
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        
        // Kosongkan input fields setelah data disimpan
        
        txtnama.setText("");
        txtharga.setText("");
        txtram.setText("");
        txtpenyimpanan.setText("");
        txtgpu.setText("");
        txtlayar.setText("");
        txtbaterai.setText("");
        tampilData();
    } catch (Exception e) {
        // Tampilkan pesan kesalahan jika terjadi kesalahan
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } 
} else {
    // Tampilkan pesan kesalahan jika ada nilai yang kosong
    JOptionPane.showMessageDialog(this, "Semua field harus diisi.", "Error", JOptionPane.ERROR_MESSAGE);
}



    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        // Ambil nilai dari input fields dan combo box
    String nama = txtnama.getText();
    String harga = txtharga.getText();
    String ram = txtram.getText();
    String penyimpanan = txtpenyimpanan.getText();
    String gpu = txtgpu.getText();
    String layar = txtlayar.getText();
    String baterai = txtlayar.getText();

    // Dapatkan baris yang dipilih dari tabel
    int selectedRow = tblAlternatif.getSelectedRow();
    if (selectedRow != -1) {
        // Dapatkan id dari baris yang dipilih
        int id = Integer.parseInt(tblAlternatif.getValueAt(selectedRow, 0).toString());

        if (!nama.isEmpty() && !harga.isEmpty() && !ram.isEmpty() && !penyimpanan.isEmpty() && !gpu.isEmpty() && !layar.isEmpty() && !baterai.isEmpty()) {
            try {
                // Update data di database
                Connection kon = koneksi.koneksiDB();
                String sql = "UPDATE alternatif SET nama = ?, harga = ?, ram = ?, penyimpanan = ?, gpu = ?, layar = ?, baterai = ? WHERE id = ?";
                PreparedStatement pst = kon.prepareStatement(sql);
                pst.setString(1, nama);
                pst.setString(2, harga);
                pst.setString(3, ram);
                pst.setString(4, penyimpanan);
                pst.setString(5, gpu);
                pst.setString(6, layar);
                pst.setString(7,baterai);
                pst.setInt(8, id);
                pst.executeUpdate();

                // Perbarui tabel tampilan setelah data diupdate
                DefaultTableModel model = (DefaultTableModel) tblAlternatif.getModel();
                model.setValueAt(nama, selectedRow, 1);
                model.setValueAt(harga, selectedRow, 2);
                model.setValueAt(ram, selectedRow, 3);
                model.setValueAt(penyimpanan, selectedRow, 4);
                model.setValueAt(gpu, selectedRow, 5);
                model.setValueAt(layar, selectedRow, 6);
                model.setValueAt(baterai, selectedRow, 7);
                
                

//                 Kosongkan input fields setelah data disimpan
                txtnama.setText("");
                txtharga.setText("");
                txtram.setText("");
                txtpenyimpanan.setText("");
                txtgpu.setText("");
                txtlayar.setText("");
                txtbaterai.setText("");
                
                tampilData();

                JOptionPane.showMessageDialog(this, "Data berhasil diupdate.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Harap isi semua field sebelum menyimpan data.", "Input Kosong", JOptionPane.WARNING_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Harap pilih data yang ingin diupdate dari tabel.", "Tidak Ada Data Terpilih", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
          mainapp i = new mainapp();
        i.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
       hapusdata();
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txtbateraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbateraiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbateraiActionPerformed

    private void hapusdata(){
        
    int row = tblAlternatif.getSelectedRow();
    
    if (row >= 0) {
        DefaultTableModel model = (DefaultTableModel) tblAlternatif.getModel();
        String id = model.getValueAt(row, 0).toString();  // Ambil ID dari baris yang dipilih
        
        // Hapus dari database\
        Connection kon = null;
        PreparedStatement pstmt = null;
    
        try {
        // Dapatkan koneksi dari kelas Koneksi
        kon = koneksi.koneksiDB();
        
            String query = "DELETE FROM alternatif WHERE id=?";
            PreparedStatement ps = kon.prepareStatement(query);
            ps.setString(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus dari database");

            // Hapus dari tabel
            model.removeRow(row);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus dari database: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(rootPane, "Pilih baris yang ingin dihapus");
    }
}

    
    public void tampilData() {
    DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("No");
    tbl.addColumn("Nama");
    tbl.addColumn("Harga");
    tbl.addColumn("ram");
    tbl.addColumn("penyimpanan");
    tbl.addColumn("gpu");
    tbl.addColumn("layar");
    tbl.addColumn("baterai");
    
   
    try {
        Connection conn = koneksi.koneksiDB();
        String sql = "SELECT * FROM alternatif";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        int no = 1;
        while (rs.next()) {
            tbl.addRow(new Object[]{ 
                no++,
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8),
            });
        }

        tblAlternatif.setModel(tbl);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data: " + e.getMessage());
        e.printStackTrace();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputalternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputalternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputalternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputalternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputalternatif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlternatif;
    private javax.swing.JTextField txtbaterai;
    private javax.swing.JTextField txtgpu;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtlayar;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpenyimpanan;
    private javax.swing.JTextField txtram;
    // End of variables declaration//GEN-END:variables

    private void tblAlternatif() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
